force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/Portions__c.field-meta.xml
<CustomField>
    <fullName>Portions__c</fullName>
    <label>Portions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrderController.cls
public with sharing class OrderController {
    public OrderController() {

    }

/*    @AuraEnabled
    public static List<Order__c> methodName(){
        
    }*/
    @AuraEnabled(cacheable=true)
    public static List<Group__c> getGroups(){
        return [SELECT Id, Name 
                FROM Group__c
                WITH SECURITY_ENFORCED];
    }

    @AuraEnabled
    public static Id insertOrder(){
        Order__c order = new Order__c();
        try {
            insert order;
            return order.Id;
        } catch (DmlException e) {
            return '0';
        }
    }

    @AuraEnabled
    public static Id insertOrderItem(
                                    Id orderId, 
                                    String name,
                                    String comment,
                                    Integer portions,
                                    Integer cost,
                                    String description,
                                    Integer num){
                                        
        OrderItem__c orderItem = new OrderItem__c(
            Order__c = orderId,
            Comment__c = comment,
            Cost__c = cost,
            Description__c = description,
            Num__c = num,
            Name = name,
            Portions__c = portions
        );
        insert orderItem;
        return orderItem.Id;

        
    }

   /* @AuraEnabled
    public static List<OrderItem__c> getOrderItemsById(Id ){
        
    }*/



}